wallpaper {
  monitor = HDMI-A-2
  path = /home/william/Downloads/17995523_57Z_2107.w026.n002.636B.p1.636.jpg
  fit_mode = cover
}

# optional fallback if you ever add more monitors
wallpaper {
  monitor =
  path = /home/william/Downloads/17995523_57Z_2107.w026.n002.636B.p1.636.jpg
  fit_mode = cover
}
