wallpaper {
  monitor = HDMI-A-2
  path = /home/william/.config/hypr/wallpapers/26-tahoe-beach/26-Tahoe-Beach-Day.png
  fit_mode = cover
}

wallpaper {
  monitor =
  path = /home/william/.config/hypr/wallpapers/26-tahoe-beach/26-Tahoe-Beach-Day.png
  fit_mode = cover
}
