wallpaper {
  monitor = desc:HP Inc. HP P34hc G4 CNC049181P
  path = /home/william/.config/hypr/wallpapers/26-tahoe-beach/26-Tahoe-Beach-Day.png
  fit_mode = cover
}

wallpaper {
  monitor =
  path = /home/william/.config/hypr/wallpapers/26-tahoe-beach/26-Tahoe-Beach-Day.png
  fit_mode = cover
}
