# Hyprlock lock screen

$font = SF Pro Display Bold
$fg = rgba(197, 236, 206, 0.88)
$accent = rgba(249, 226, 135, 0.88)

# BACKGROUND
background {
    monitor =
    path = ~/.cache/hyprlock/wallpaper.png
    blur_passes = 0
    blur_size = 0
    noise = 0.0
    contrast = 0.8916
    brightness = 0.8172
}

# GENERAL
general {
    screencopy_mode = 1
}

animations {
    enabled = true
    bezier = fluid, 0.45, 0, 0.55, 1

    animation = fadeIn, 1, 6, fluid    
    animation = fadeOut, 1, 6, fluid
    animation = inputFieldDots, 1, 2, linear
    animation = inputFieldColors, 1, 8, fluid
    animation = inputFieldFade, 1, 8, fluid
    animation = inputFieldWidth, 1, 8, fluid
}

# Profile photo
image {
    monitor =
    path = ~/.config/hypr/hyprlock/avatar.jpg
    border_size = 3
    border_color = rgba(197, 236, 206, 0.35)
    size = 170
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 0, 10
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $fg
    font_size = 24
    font_family = $font
    position = 0, 265
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = $accent
    font_size = 72
    font_family = $font
    position = 0, 180
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = $fg
    font_size = 21
    font_family = $font
    position = 0, -95
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 340, 54
    fade_on_empty = false
    fade_timeout = 10000
    font_family = $font
    font_color = $accent
    outline_thickness = 2   
    dots_size = 0.2 
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 198, 0, 0.8)
    fail_color = rgba(220, 0, 0, 0.8)
    inner_color = rgba(220, 198, 110, 0.2)
    placeholder_text = <i><span foreground="##c5ecce">Start typing pass...</span></i>
    hide_input = false
    capslock_color = rgba(255, 180, 171, 0.8)
    numlock_color = rgba(255, 180, 171, 0.8)
    position = 0, -165
    halign = center
    valign = center
}
